file=src/main/resources/test.txt
ticker-user-update=ON
conditional.property=false

#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#hibernate.connection.driver_class=org.postgresql.Driver
#hibernate.connection.url=jdbc:postgresql://localhost:5432/my_ticket_service_db
#hibernate.connection.username=postgres
#hibernate.connection.password=1
#hibernate.show_sql=true
#hibernate.hbm2ddl=update

spring.datasource.url=jdbc:postgresql://localhost:5432/my_ticket_service_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.hibernate.show_sql=true
spring.hibernate.hbm2ddl=update